### ISSUE TITLE
Cannot process is all

### ISSUE THREAD

**Issue by prashantdwivedi** [coursera-dl/coursera-dl#808]
Traceback (most recent call last):
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/coursera_dl.py", line 247, in main
    error_occurred, completed = download_class(
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/coursera_dl.py", line 134, in download_on_demand_class
    error_occurred, modules = extractor.get_modules(
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/extractors.py", line 53, in get_modules
    error_occurred, modules = self._parse_on_demand_syllabus(
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/extractors.py", line 161, in _parse_on_demand_syllabus
    links = course.extract_links_from_supplement(
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/api.py", line 1268, in extract_links_from_supplement
    supplement_content, self._extract_links_from_text(value))
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/api.py", line 1522, in _extract_links_from_text
    self._extract_links_from_asset_tags_in_text(text))
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/api.py", line 1550, in _extract_links_from_asset_tags_in_text
    title = clean_filename(
  File "/Users/prashantdwivedi/Downloads/c-dl/coursera-dl/coursera/utils.py", line 118, in clean_filename
    s = h.unescape(s)
AttributeError: 'HTMLParser' object has no attribute 'unescape'

**Comment by yahyasarhan** [comment]
I am also having the same issue

**Comment by ghost** [comment]
me too

**Comment by whisperingkahuna** [comment]
same here.

**Comment by whisperingkahuna** [comment]
> same here.

Guys its working with downgrading python version to 3.8.0
`conda install python==3.8.0`

**Comment by elevul** [comment]
Same issue

**Comment by whisperingkahuna** [comment]
> Same issue

@elevul 
Check if your python version is 3.8.0. if not downgrade to version 3.8.0, it will work.
I had the same issue but sorted it out by downgrading Python to 3.8.0

**Comment by elevul** [comment]
> > Same issue
> 
> @elevul Check if your python version is 3.8.0. if not downgrade to version 3.8.0, it will work. I had the same issue but sorted it out by downgrading Python to 3.8.0

Yeah, fixed by downgrading to 3.8.10 but now other scripts are broken because they need 3.9...
This is becoming a bit frustrating :D

**Comment by whisperingkahuna** [comment]
> 

It worked for me for another device as well.  Try to make a new environment, download _coursera-dl_ there, it should work!
Below is the list of libraries I got, when I installed _coursera-dl_. 
![image](https://user-images.githubusercontent.com/28399678/143670645-b01fff65-5610-42ab-a4b5-7c9544b0ce2c.png)

**Comment by whisperingkahuna** [comment]
> > 
> 
> It worked for me for another device as well. Try to make a new environment, download _coursera-dl_ there, it should work! Below is the list of libraries I got, when I installed _coursera-dl_. ![image](https://user-images.githubusercontent.com/28399678/143670645-b01fff65-5610-42ab-a4b5-7c9544b0ce2c.png)


Also, try this if you still have issues. 
[link](https://github.com/coursera-dl/coursera-dl/issues/804#issuecomment-922260417)
I am using it CAUTH parameter, as explained in the link above  

`With CAUTH parameter:	 coursera-dl -ca 'some-ca-value-from-browser' modelthinking-004`

**Comment by tudorelu** [comment]
Can confirm that this works with python3.8.
