### ISSUE TITLE
SSLV3 alert handshake failure on coursera

### ISSUE THREAD

**Issue by gamegogo** [coursera-dl/coursera-dl#383]
Was trying to download coursera course number algo-004, but got this error message. What should I do?

**Comment by balta2ar** [comment]
I could not reproduce the problem in my environment. Can you provide a stack trace or a way to reproduce the problem? Is the problem consistent.

**Comment by anchoo2kewl** [comment]
I got the same error. Here's a stack trace:

```shell
    Starting new HTTPS connection (1): www.coursera.org
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 942, in main
    result = download_on_demand_class(args, class_name)
  File "/usr/local/lib/python2.7/dist-packages/coursera/coursera_dl.py", line 885, in download_on_demand_class
    login(session, args.username, args.password)
  File "/usr/local/lib/python2.7/dist-packages/coursera/cookies.py", line 115, in login
    headers=headers, allow_redirects=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508,
in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465,
in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573,
in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 431,
in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
```

**Comment by anchoo2kewl** [comment]
The problem is due to the  vulnerability in SSL_v3 named POODLE which makes it insecure. I guess COursera patched the bug and hence TLSv1 was not working with Python 2.7.6 anymore. Upgrading to 2.7.9. did the trick. Read more on the issue: (https://github.com/coursera-dl/coursera-dl/issues/322)

**Comment by haisum** [comment]
On my ubuntu, I solved issue by using `virtualenv` with python3

```bash
sudo easy_install virtualenv
virtualenv -p /usr/bin/python3 coursera
cd coursera/
./bin/pip install coursera
./bin/coursera-dl -u username@gmail.com -p password --on-demand machine-learning
```
worked fine then.

**Comment by rbrito** [comment]
@haisum, thanks for confirming that Python 3 makes everything work for you.

For everybody else that may be experiencing the problem, could you please post your results of the document at https://github.com/coursera-dl/coursera-dl/issues/377#issuecomment-131268395 to issue #377?  I would *really* appreciate any extra information that you can provide, since that would make it easier to find what varies and what doesn't with the various systems that exhibit the problem.

In fact, even if people have worked around the problem with Python 3, but can still reproduce the problem with Python 2 would be welcome to post the difference in their setups.

I'm closing this bug report as it seems a duplicate of that problem.

Again, please post extra information to issue #377.

Thank you very much,

Rogério.

**Comment by s4sarath** [comment]
@haisum - That was a great workaround . Working like charm .
